[project]
name = "home-test-rest-api"
requires-python = ">=3.12"

[tool.ruff]
line-length = 100

[tool.ruff.lint]
select = ["A", "B", "C90", "E", "F", "I", "N", "PT", "PTH", "RET", "RUF", "SIM", "UP", "W"]

[tool.ruff.lint.mccabe]
max-complexity = 5
